/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Java.ListRandom;
import Java.koneksi;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author 7
 */
public class Master_Salesman_TambahSalesman extends javax.swing.JFrame {

    private String kode, nama, contact, telepon, alamat, kota;
    private Java.koneksi koneksi;
    private Java.ListRandom list;
    private Connection con;
    private ResultSet hasil;
    private Statement stat;
    private String dataTombol, radio;
    private int status_sales;
    
    public Master_Salesman_TambahSalesman() {
        initComponents();
        this.setLocationRelativeTo(null);
        fNama.requestFocusInWindow();
        list = new ListRandom();
        kode = ListRandom.getKode_salesman();
        dataTombol = list.getTombol_salesman();
        System.out.println(kode+"master");
        System.out.println(dataTombol+"master");
        if(dataTombol=="edit"){
            fTidakAktif.hide();
            fAktif.hide();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        fAlamat = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        fKota = new javax.swing.JTextField();
        fContact = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        fSimpan = new javax.swing.JButton();
        fBatal = new javax.swing.JButton();
        fTelepon = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        fTidakAktif = new javax.swing.JRadioButton();
        fAktif = new javax.swing.JRadioButton();
        fNama = new javax.swing.JTextField();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(358, 330));
        setResizable(false);
        setSize(new java.awt.Dimension(358, 330));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        fAlamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fAlamat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fAlamatKeyPressed(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel64.setText("Nama");

        fKota.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fKota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fKotaActionPerformed(evt);
            }
        });
        fKota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fKotaKeyPressed(evt);
            }
        });

        fContact.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fContactKeyPressed(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel66.setText("Kota");

        fSimpan.setBackground(new java.awt.Color(85, 222, 93));
        fSimpan.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/if_stock_save_20659.png"))); // NOI18N
        fSimpan.setText("Simpan");
        fSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSimpanActionPerformed(evt);
            }
        });
        fSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fSimpanKeyPressed(evt);
            }
        });

        fBatal.setBackground(new java.awt.Color(255, 51, 51));
        fBatal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/if_document_delete_61766.png"))); // NOI18N
        fBatal.setText("Batal");
        fBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fBatalActionPerformed(evt);
            }
        });
        fBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fBatalKeyPressed(evt);
            }
        });

        fTelepon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fTeleponKeyPressed(evt);
            }
        });

        jLabel67.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel67.setText("Telepon");

        jLabel65.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel65.setText("Alamat");

        jLabel68.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel68.setText("Contact");

        jLabel63.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel63.setText("Tambah / Update Salesman");

        buttonGroup1.add(fTidakAktif);
        fTidakAktif.setText("Tidak Aktif");
        fTidakAktif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fTidakAktifKeyPressed(evt);
            }
        });

        buttonGroup1.add(fAktif);
        fAktif.setText("Aktif");
        fAktif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fAktifKeyPressed(evt);
            }
        });

        fNama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        fNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fNamaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel63)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel66, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel67)
                                    .addGap(30, 30, 30)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel65)
                                    .addComponent(jLabel64)
                                    .addComponent(jLabel68))
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fBatal))
                            .addComponent(fContact)
                            .addComponent(fKota)
                            .addComponent(fAlamat)
                            .addComponent(fTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fTidakAktif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fAktif))
                            .addComponent(fNama))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel63)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(fNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(fAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel66)
                    .addComponent(fKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(fTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(fContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTidakAktif)
                    .addComponent(fAktif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSimpan)
                    .addComponent(fBatal))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(375, 351));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fKotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fKotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fKotaActionPerformed

    private void fSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSimpanActionPerformed
        list = new ListRandom();
        dataTombol = list.getTombol_salesman();
        kode = list.getKode_salesman();
        System.out.println("fsimpan");
        System.out.println(dataTombol+kode);
        if(dataTombol=="edit"){
            System.out.println("/");
            edit();
            System.out.println("//");
        }else{
            simpan();
        }
    }//GEN-LAST:event_fSimpanActionPerformed

    private void fBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBatalActionPerformed
       this.dispose();
       bersih();
    }//GEN-LAST:event_fBatalActionPerformed

    private void fAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fAlamatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fKota.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fAlamatKeyPressed

    private void fKotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fKotaKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fTelepon.requestFocusInWindow();
       }
       if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fKotaKeyPressed

    private void fTeleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTeleponKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fContact.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fTeleponKeyPressed

    private void fContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fContactKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           list = new ListRandom();
            dataTombol = list.getTombol_salesman();
            kode = list.getKode_salesman();
            System.out.println("fsimpan");
            System.out.println(dataTombol+kode);
            if(dataTombol=="edit"){
                fSimpan.requestFocusInWindow();
            }else{
                fTidakAktif.requestFocusInWindow();
                fTidakAktif.setSelected(true);
            }
            
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
        
        
    }//GEN-LAST:event_fContactKeyPressed

    private void fTidakAktifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fTidakAktifKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {     
           fAktif.requestFocusInWindow();
           fAktif.setSelected(true);
       }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fSimpan.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fTidakAktifKeyPressed

    private void fAktifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fAktifKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {     
           fTidakAktif.requestFocusInWindow();
           fTidakAktif.setSelected(true);
       }
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fSimpan.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fAktifKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        kode=null;
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        kode= null;
    }//GEN-LAST:event_formWindowClosing

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            dispose();
            bersih();
        }
    }//GEN-LAST:event_formKeyPressed

    private void fSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fSimpanKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
            list = new ListRandom();
            dataTombol = list.getTombol_salesman();
            kode = list.getKode_salesman();
            System.out.println("fsimpan");
            System.out.println(dataTombol+kode);
            if(dataTombol=="edit"){
                System.out.println("/");
                edit();
                System.out.println("//");
            }else{
                simpan();
            }
       }
    }//GEN-LAST:event_fSimpanKeyPressed

    private void fBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fBatalKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fBatalKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setFocusable(true);
        fNama.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void fNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNamaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fAlamat.requestFocusInWindow();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            bersih();
        }
    }//GEN-LAST:event_fNamaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_Salesman_TambahSalesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_Salesman_TambahSalesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_Salesman_TambahSalesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_Salesman_TambahSalesman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_Salesman_TambahSalesman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton fAktif;
    public javax.swing.JTextField fAlamat;
    private javax.swing.JButton fBatal;
    public javax.swing.JTextField fContact;
    public javax.swing.JTextField fKota;
    public javax.swing.JTextField fNama;
    private javax.swing.JButton fSimpan;
    public javax.swing.JTextField fTelepon;
    private javax.swing.JRadioButton fTidakAktif;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void simpan(){
        nama = fNama.getText();
        contact = fContact.getText();
        telepon = fTelepon.getText();
        alamat = fAlamat.getText();
        kota = fKota.getText();
        radioButton();
        if(radio == "Tidak Aktif"){
            status_sales = 0;
        }else{
            status_sales = 1;
        }
        try{
            int angka = 0;
            String query= "SELECT kode_salesman, SUBSTRING(kode_salesman,1,4) "
                        + "* 1 AS URUT FROM salesman ORDER BY URUT DESC LIMIT 1";
            koneksi = new koneksi();
            hasil = koneksi.ambilData(query);
            while(hasil.next()){
                kode = hasil.getString("kode_salesman");
                System.out.println(angka);

                angka = Integer.parseInt(kode)+1;
                System.out.println("id"+angka);


                String sql= "Insert into salesman values ('"+angka+"', '"+nama+"', "
                        + "'"+alamat+"', '"+kota+"', '"+telepon+"', '"+contact+"', '"+status_sales+"', '"+nama+"', '0', '0' )";
                System.out.println(sql);
                koneksi.simpanData(sql);

                JOptionPane.showMessageDialog(null,"Data sukses di input");
                bersih();
                this.dispose();
            }

        }catch (SQLException e){
            System.out.println();
        }
    }

    private void edit(){
        try {
            koneksi = new koneksi();
            String sql= "Update salesman set nama_salesman=?, contact_salesman=?, "
                    + "telepon_salesman=?, alamat=?, kota_salesman=? where kode_salesman=?" ;
            PreparedStatement p = (PreparedStatement) koneksi.Connect().prepareStatement(sql);
                p.setString(1, fNama.getText());
                p.setString(2, fContact.getText());
                p.setString(3, fTelepon.getText());
                p.setString(4, fAlamat.getText());
                p.setString(5, fKota.getText());
                p.setString(6, kode);
                p.executeUpdate();

                this.dispose();
                System.out.print(p);
                JOptionPane.showMessageDialog(null,"Data sukses di edit");
                bersih();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
     private void bersih(){
        kode = "0";
        dataTombol = "";
        fTelepon.setText("");
        fNama.setText("");
        fContact.setText("");
        fAlamat.setText("");
        fKota.setText("");
    }
     
     private void radioButton(){
        if (fTidakAktif.isSelected()){
            radio = fTidakAktif.getText();
            System.out.println(radio);
        }else{
            radio = fAktif.getText();
            System.out.println(radio);
        }
    }
}
