/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Java.ListPegawai;
import Java.koneksi;
import Java.modelTabelPegawai;
import Java.modelTabelSupplier;
import static UI.Master_Supplier.a;
import static UI.Master_Supplier.angka;
import static UI.Master_Supplier.nilai_status;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;  
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author 7
 */
public class Master_Pegawai extends javax.swing.JFrame {

    private Java.koneksi koneksi;
    private Connection con;
    private ResultSet hasil;
    private Statement stat;
    private Java.ListPegawai listPegawai;
    private List<Java.ListPegawai> list; 
    private TableModel model;
    private String query;
    private int id, kode_lokasi_update;
    private String nama_pegawai, alamat_pegawai, kota_pegawai, telepon_pegawai, contact_pegawai,kode_lokasi;
    private int kode_unik, kode_pegawai;
    public Master_Pegawai() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampilTabel();
        fCari.requestFocusInWindow();
    }
    Master_Pegawai_TambahPegawai pegawai_edit=new Master_Pegawai_TambahPegawai();
        public String tampilTabel() {
        String data = "";
        koneksi = new koneksi();
        con = (Connection) koneksi.Connect();
        try {
            data = "SELECT kode_pegawai, kode_unik, nama_lokasi, nama_pegawai, alamat_pegawai, kota_pegawai, telepon_pegawai,contact_pegawai FROM pegawai,lokasi WHERE pegawai.kode_lokasi=lokasi.kode_lokasi order by kode_pegawai";
            System.out.println(data);
            hasil = koneksi.ambilData(data);
            System.out.println("sukses query tampil tabel");
            setModel(hasil);
            
        } catch (Exception e) {
            System.out.println("Error tampil tabel");
        }
        return data;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        fTabel = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        fCari = new javax.swing.JTextField();
        jLabel184 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton13.setBackground(new java.awt.Color(71, 166, 227));
        jButton13.setText("penggajian");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(71, 166, 227));
        jButton14.setText("menu");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(71, 166, 227));
        jButton12.setText("login");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        fTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Unik", "Nama ", "Lokasi", "Alamat", "Kota", "Telepon", "Contact"
            }
        ));
        jScrollPane7.setViewportView(fTabel);

        jButton11.setBackground(new java.awt.Color(71, 166, 227));
        jButton11.setText("edit");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(71, 166, 227));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Tambah Pegawai");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        fCari.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cari", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        fCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fCariKeyReleased(evt);
            }
        });

        jLabel184.setText("Refresh");
        jLabel184.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel184MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 885, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fCari, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel184, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel184))
                    .addComponent(fCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(49, 112, 143));
        jLabel24.setText("tanggal");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(49, 112, 143));
        jLabel23.setText("Pegawai form");

        jLabel25.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(49, 112, 143));
        jLabel25.setText("waktu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 763, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25))
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1092, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
 Master_Pegawai_penggajian pp=new Master_Pegawai_penggajian();
 pp.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
Master_Pegawai_Menu pm=new Master_Pegawai_Menu();
 pm.setVisible(true); 
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        Master_Login log=new Master_Login();
        log.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//        Master_Pegawai_TambahPegawai tp=new Master_Pegawai_TambahPegawai();
//        tp.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
         try {
            buatnomor();
            a=1;
        } catch (SQLException ex) {
            Logger.getLogger(Master_Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
       pegawai_edit.fKodePegawai.setText(Integer.toString(id));
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
         if (fTabel.getSelectedRow()<0) {
            JOptionPane.showMessageDialog(null,"Pilih Pegawai yang akan diedit");
        } else {
             try {
                 pegawai_edit.setVisible(true);
                 ambilDataTabel();
                 pegawai_edit.fKodePegawai.setText(Integer.toString(kode_pegawai));
                 pegawai_edit.fKodeUnikP.setText(Integer.toString(kode_unik));
                 pegawai_edit.fNamaP.setText(nama_pegawai);
                 pegawai_edit.fLokasiP.setSelectedItem(kode_lokasi);
                 pegawai_edit.fAlamatP.setText(alamat_pegawai);
                 pegawai_edit.fKotaP.setSelectedItem(kota_pegawai);
                 pegawai_edit.fTeleponP.setText(telepon_pegawai);
                 pegawai_edit.fContactP.setText(contact_pegawai);
                 query = "SELECT status_pegawai FROM pegawai where nama_pegawai='" + nama_pegawai + "' and kode_pegawai=" + kode_pegawai;
                 hasil = koneksi.ambilData(query);
                 while (hasil.next()) {
                     nilai_status = hasil.getInt("status_pegawai");
                     System.out.println("nilai status"+nilai_status);
                     if (nilai_status == 0) {
                         pegawai_edit.fACTIVE.setSelected(true);
                     } else {
                         pegawai_edit.fDEACTIVE.setSelected(true);
                     }
                 }
                 a=2;
             } catch (Exception ex) {
                 Logger.getLogger(Master_Supplier.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
    }//GEN-LAST:event_jButton11MouseClicked

    private void fCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fCariKeyReleased
//        try{
//            query = "SELECT kode_pegawai, kode_unik, nama_lokasi, nama_pegawai, alamat_pegawai, kota_pegawai, telepon_pegawai,contact_pegawai FROM pegawai,lokasi order by kode_pegawai having  nama_pegawai like '%" + fCari.getText() + "%' or alamat_pegawai like '%"+fCari.getText()+"%' or kota_pegawai like '%"+fCari.getText()+"%' ";
//            hasil = koneksi.ambilData(query);
//            setModel(hasil);
//            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
//                fTabel.requestFocusInWindow();
//            }
//        } catch (Exception e) {
//    }
    }//GEN-LAST:event_fCariKeyReleased

    private void jLabel184MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel184MouseClicked
      tampilTabel();
    }//GEN-LAST:event_jLabel184MouseClicked
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_Pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_Pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fCari;
    private javax.swing.JTable fTabel;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
    public void setModel(ResultSet hasil) {
        try {
            list = new ArrayList<Java.ListPegawai>();
            while (hasil.next()) {
                listPegawai = new Java.ListPegawai();
                listPegawai.setKode_pegawai(hasil.getInt("kode_pegawai"));
                listPegawai.setKode_unik(hasil.getInt("kode_unik"));
                listPegawai.setNama_pegawai(hasil.getString("nama_pegawai"));
                listPegawai.setKode_lokasi(hasil.getString("nama_lokasi"));
                listPegawai.setAlamat_pegawai(hasil.getString("alamat_pegawai"));
                listPegawai.setKota_pegawai(hasil.getString("kota_pegawai"));
                listPegawai.setTelepon_pegawai(hasil.getString("telepon_pegawai"));
                listPegawai.setContact_pegawai(hasil.getString("contact_pegawai"));
                list.add(listPegawai);
            }
            model = new modelTabelPegawai(list);
            fTabel.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
  private void buatnomor() throws SQLException{
        query = "SELECT kode_pegawai FROM pegawai ORDER BY kode_pegawai DESC LIMIT 1";
        hasil = koneksi.ambilData(query);
        while(hasil.next()){   
            angka = hasil.getInt("kode_pegawai");
            id=angka+1;
            System.out.println("angka baru : "+id);
            pegawai_edit.setVisible(true);
            pegawai_edit.fKodePegawai.setText(Integer.toString(id));
         }
    }   
   private void ambilDataTabel(){
        int row= fTabel.getSelectedRow();
        kode_pegawai  = ((Integer)fTabel.getValueAt(row, 0));
        kode_unik = ((Integer)fTabel.getValueAt(row, 1));
        nama_pegawai = ((String)fTabel.getValueAt(row, 2));
        kode_lokasi = ((String)fTabel.getValueAt(row, 3));
        alamat_pegawai = ((String)fTabel.getValueAt(row, 4));
        kota_pegawai = ((String)fTabel.getValueAt(row, 5));
        telepon_pegawai = ((String)fTabel.getValueAt(row, 6));
        contact_pegawai = ((String)fTabel.getValueAt(row, 7));
    } 
    public void edit(int kode_pegawai,int kode_unik,String nama,int lokasinew,String lokasi,String alamat,String kota,String telepon,String contact,int status) throws SQLException {
           
            if (a==2) {
                if(lokasi.equals("Pusat")){
                    kode_lokasi_update=1;
                }else if(lokasi .equals("GUD63")){
                    kode_lokasi_update=2;
                }else if(lokasi.equals("TOKO")){
                    kode_lokasi_update=4;
                }else if(lokasi.equals("TENGAH")){
                    kode_lokasi_update=5;
                }else if(lokasi.equals("UTARA")){
                    kode_lokasi_update=6;
                }
                String sql = "Update pegawai set kode_unik="+kode_unik+",nama_pegawai = '" + nama + "',kode_lokasi=" +kode_lokasi_update +
                        ",alamat_pegawai='" + alamat + "',kota_pegawai='" +kota + "',telepon_pegawai='" + telepon + "',contact_pegawai='" + contact + "', status_pegawai="+status+" where kode_pegawai=" + kode_pegawai;
                System.out.println(sql);
                koneksi.simpanData(sql);
                tampilTabel();
                JOptionPane.showMessageDialog(null, "Data sukses di edit");
                tampilTabel();
            }if(a==1){
                angka = 0;
                if(lokasi == "Pusat"){
                    kode_lokasi_update=1;
                }else if(lokasi == "GUD63"){
                    kode_lokasi_update=2;
                }else if(lokasi == "TOKO"){
                    kode_lokasi_update=4;
                }else if(lokasi == "TENGAH"){
                    kode_lokasi_update=5;
                }else if(lokasi == "UTARA"){
                    kode_lokasi_update=6;
                }
                System.out.println("kode last"+kode_lokasi_update);
                String sql = "Insert into pegawai values ("+kode_pegawai + "," + kode_unik + "," + lokasinew + ",0,'" + nama + "','" + alamat + "','" + kota + "','" + telepon + "','"+contact+"',"+status+",'','');";
                System.out.println(sql);
                koneksi.simpanData(sql);
                JOptionPane.showMessageDialog(null, "Data sukses di simpan");
                tampilTabel();
          }
 }
     public void bersih(){
        pegawai_edit.fKodePegawai.setText("");
        pegawai_edit.fKodeUnikP.setText("");
        pegawai_edit.fNamaP.setText("");
        pegawai_edit.fLokasiP.setSelectedItem("");
        pegawai_edit.fAlamatP.setText("");
        pegawai_edit.fKotaP.setSelectedItem("");
        pegawai_edit.fTeleponP.setText("");
        pegawai_edit.fContactP.setText("");
    }
       
}
