/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Java.ListTOP;
import Java.koneksi;
import com.mysql.jdbc.Connection;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 7
 */
public class Master_TOP_tambahTOP extends javax.swing.JFrame {

    private Java.koneksi koneksi;
    private Connection con;
    private ResultSet hasil;
    private Statement stat;
    private int id;
    private String nama_top;
    private Master_TOP mt;
    
    public Master_TOP_tambahTOP() {
        initComponents();
        this.setLocationRelativeTo(null);
        fHari.requestFocusInWindow();
    }
    
    public void ambilData(){
        ListTOP list = new ListTOP();
        id = list.getId_top();
        nama_top = list.getNama_top();
        if(id!=0){
            fHari.setText(nama_top);
            System.out.println(id);
        }else{
            fHari.setText(nama_top);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel69 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        fHari = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        fSimpan = new javax.swing.JButton();
        fBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel69.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel69.setText("Tambah / Update TOP");

        jLabel71.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel71.setText("Hari");

        fHari.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fHari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fHariKeyPressed(evt);
            }
        });

        fSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/if_stock_save_20659.png"))); // NOI18N
        fSimpan.setText("Simpan");
        fSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fSimpanActionPerformed(evt);
            }
        });
        fSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fSimpanKeyPressed(evt);
            }
        });

        fBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/if_document_delete_61766.png"))); // NOI18N
        fBatal.setText("Batal");
        fBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fBatalActionPerformed(evt);
            }
        });
        fBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fBatalKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel69))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel71)
                                .addGap(51, 51, 51)
                                .addComponent(fHari, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(fSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fBatal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel69)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(fHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fSimpan)
                    .addComponent(fBatal))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(343, 213));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fSimpanActionPerformed
        simpan();
    }//GEN-LAST:event_fSimpanActionPerformed

    private void fHariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fHariKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           fSimpan.requestFocusInWindow();
       }
         if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
             bersih();
        }
    }//GEN-LAST:event_fHariKeyPressed

    private void fBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBatalActionPerformed
        this.dispose();
        id=0;
    }//GEN-LAST:event_fBatalActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ambilData();
        fHari.requestFocusInWindow();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        id = 0;
        fHari.setText("");
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        id = 0;
        fHari.setText("");
    }//GEN-LAST:event_formWindowClosing

    private void fSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fSimpanKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {     
           simpan();
       }
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            id=0;
        }
    }//GEN-LAST:event_fSimpanKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
       if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            id=0;
        }
    }//GEN-LAST:event_formKeyPressed

    private void fBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fBatalKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
            setVisible(false);
            id = 0;
        }
    }//GEN-LAST:event_fBatalKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Master_TOP_tambahTOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Master_TOP_tambahTOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Master_TOP_tambahTOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Master_TOP_tambahTOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Master_TOP_tambahTOP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fBatal;
    private javax.swing.JTextField fHari;
    private javax.swing.JButton fSimpan;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void simpan(){
        System.out.println("aaa");
        System.out.println("bbb");
        if(id != 0){
            edit();
            fHari.setText(nama_top);
            System.out.println("edit");
        }else{
            koneksi = new koneksi();
            koneksi.Connect();

            String query= "SELECT id_top FROM top ORDER BY id_top DESC LIMIT 1";
            hasil = koneksi.ambilData(query);
            try{
            while(hasil.next()){
                int angka = hasil.getInt("id_top");
                System.out.println(angka);

                id = angka + 1;
                System.out.println("id"+id);
            }
            }catch(Exception e){
                System.out.println("error simpan");
            }
            String sql= "Insert into top values ('"+id+"', '"+fHari.getText()+"', '0')";
            System.out.println(sql);
            koneksi.simpanData(sql);
            bersih();
            JOptionPane.showMessageDialog(null,"Data sukses di input");
            this.dispose();
            Master_TOP mt = new Master_TOP();
            mt.dispose();
        }
        
    }
    
    private void edit(){
        try {
           String sql= "Update top set nama_top=? where id_top=?" ;
           koneksi = new koneksi();
           PreparedStatement p = (PreparedStatement) koneksi.Connect().prepareStatement(sql);
                p.setString(1, fHari.getText());
                p.setInt(2, id);
                p.executeUpdate();

                System.out.print(p);
                JOptionPane.showMessageDialog(null,"Data sukses di edit");
                this.dispose();
                bersih();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
 
    private void bersih(){
        id = 0;
        fHari.setText("");
    }
}
